### ISSUE TITLE
Incorrect return

### ISSUE THREAD

**Issue by jro31** [markburns/numbers_in_words#19]
Was just running some tests, and almost all returned correctly. I got the following return though:

`[1] pry(main)> NumbersInWords.in_numbers('a thousand six hundred and fifty-five')
=> 1161`

**Comment by markburns** [comment]
Interesting. Which version? I've been trying to improve this library a little in my spare time as a hobby. But I'm surprised that such a simple case can trip it up. I can maybe look at it tonight. Do you fancy doing a PR to add the failing spec?

**Comment by jro31** [comment]
Version 0.4.0.

Have added as a failing spec and put in a pr.

**Comment by markburns** [comment]
Fixed in 0.4.1

**Comment by dimidd** [comment]
` require 'numbers_in_words'; NumbersInWords.in_numbers('thousand six hundred and fifty five')`
=> 1161

But I'm not sure it's grammatical without the article.

**Comment by markburns** [comment]
You’re correct that it’s not. But his example didn’t skip the article.

I do think for your example we should probably raise an exception instead of returning such a strange answer. I don’t think my latest fix does anything for this example though. Only for those prefixed with ‘a’.
matz <notifications@github.com> wrote:
“ require 'numbers_in_words'; NumbersInWords.in_numbers('thousand six hundred and fifty five')
 => 1161

But I'm not sure it's grammatical without the article.”
